package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AanvraagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAanvraagAllPropertiesEquals(Aanvraag expected, Aanvraag actual) {
        assertAanvraagAutoGeneratedPropertiesEquals(expected, actual);
        assertAanvraagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAanvraagAllUpdatablePropertiesEquals(Aanvraag expected, Aanvraag actual) {
        assertAanvraagUpdatableFieldsEquals(expected, actual);
        assertAanvraagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAanvraagAutoGeneratedPropertiesEquals(Aanvraag expected, Aanvraag actual) {
        assertThat(expected)
            .as("Verify Aanvraag auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAanvraagUpdatableFieldsEquals(Aanvraag expected, Aanvraag actual) {
        assertThat(expected)
            .as("Verify Aanvraag relevant properties")
            .satisfies(e -> assertThat(e.getDatumtijd()).as("check datumtijd").isEqualTo(actual.getDatumtijd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAanvraagUpdatableRelationshipsEquals(Aanvraag expected, Aanvraag actual) {
        assertThat(expected)
            .as("Verify Aanvraag relationships")
            .satisfies(e -> assertThat(e.getVoorArchiefstuks()).as("check voorArchiefstuks").isEqualTo(actual.getVoorArchiefstuks()))
            .satisfies(e -> assertThat(e.getDoetBezoeker()).as("check doetBezoeker").isEqualTo(actual.getDoetBezoeker()));
    }
}
