package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AfwijkendcorrespondentiepostadresrolAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAfwijkendcorrespondentiepostadresrolAllPropertiesEquals(
        Afwijkendcorrespondentiepostadresrol expected,
        Afwijkendcorrespondentiepostadresrol actual
    ) {
        assertAfwijkendcorrespondentiepostadresrolAutoGeneratedPropertiesEquals(expected, actual);
        assertAfwijkendcorrespondentiepostadresrolAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAfwijkendcorrespondentiepostadresrolAllUpdatablePropertiesEquals(
        Afwijkendcorrespondentiepostadresrol expected,
        Afwijkendcorrespondentiepostadresrol actual
    ) {
        assertAfwijkendcorrespondentiepostadresrolUpdatableFieldsEquals(expected, actual);
        assertAfwijkendcorrespondentiepostadresrolUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAfwijkendcorrespondentiepostadresrolAutoGeneratedPropertiesEquals(
        Afwijkendcorrespondentiepostadresrol expected,
        Afwijkendcorrespondentiepostadresrol actual
    ) {
        assertThat(expected)
            .as("Verify Afwijkendcorrespondentiepostadresrol auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAfwijkendcorrespondentiepostadresrolUpdatableFieldsEquals(
        Afwijkendcorrespondentiepostadresrol expected,
        Afwijkendcorrespondentiepostadresrol actual
    ) {
        assertThat(expected)
            .as("Verify Afwijkendcorrespondentiepostadresrol relevant properties")
            .satisfies(e -> assertThat(e.getPostadrestype()).as("check postadrestype").isEqualTo(actual.getPostadrestype()))
            .satisfies(
                e ->
                    assertThat(e.getPostbusofantwoordnummer())
                        .as("check postbusofantwoordnummer")
                        .isEqualTo(actual.getPostbusofantwoordnummer())
            )
            .satisfies(e -> assertThat(e.getPostcodepostadres()).as("check postcodepostadres").isEqualTo(actual.getPostcodepostadres()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAfwijkendcorrespondentiepostadresrolUpdatableRelationshipsEquals(
        Afwijkendcorrespondentiepostadresrol expected,
        Afwijkendcorrespondentiepostadresrol actual
    ) {}
}
