package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AmbachtAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmbachtAllPropertiesEquals(Ambacht expected, Ambacht actual) {
        assertAmbachtAutoGeneratedPropertiesEquals(expected, actual);
        assertAmbachtAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmbachtAllUpdatablePropertiesEquals(Ambacht expected, Ambacht actual) {
        assertAmbachtUpdatableFieldsEquals(expected, actual);
        assertAmbachtUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmbachtAutoGeneratedPropertiesEquals(Ambacht expected, Ambacht actual) {
        assertThat(expected)
            .as("Verify Ambacht auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmbachtUpdatableFieldsEquals(Ambacht expected, Ambacht actual) {
        assertThat(expected)
            .as("Verify Ambacht relevant properties")
            .satisfies(e -> assertThat(e.getAmbachtsoort()).as("check ambachtsoort").isEqualTo(actual.getAmbachtsoort()))
            .satisfies(e -> assertThat(e.getJaarambachttot()).as("check jaarambachttot").isEqualTo(actual.getJaarambachttot()))
            .satisfies(e -> assertThat(e.getJaarambachtvanaf()).as("check jaarambachtvanaf").isEqualTo(actual.getJaarambachtvanaf()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmbachtUpdatableRelationshipsEquals(Ambacht expected, Ambacht actual) {}
}
