package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BehandelsoortAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBehandelsoortAllPropertiesEquals(Behandelsoort expected, Behandelsoort actual) {
        assertBehandelsoortAutoGeneratedPropertiesEquals(expected, actual);
        assertBehandelsoortAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBehandelsoortAllUpdatablePropertiesEquals(Behandelsoort expected, Behandelsoort actual) {
        assertBehandelsoortUpdatableFieldsEquals(expected, actual);
        assertBehandelsoortUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBehandelsoortAutoGeneratedPropertiesEquals(Behandelsoort expected, Behandelsoort actual) {
        assertThat(expected)
            .as("Verify Behandelsoort auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBehandelsoortUpdatableFieldsEquals(Behandelsoort expected, Behandelsoort actual) {
        assertThat(expected)
            .as("Verify Behandelsoort relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBehandelsoortUpdatableRelationshipsEquals(Behandelsoort expected, Behandelsoort actual) {}
}
