package nl.ritense.demo.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class BeheerobjectTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static Beheerobject getBeheerobjectSample1() {
        return new Beheerobject()
            .id(1L)
            .aangemaaktdoor("aangemaaktdoor1")
            .beheergebied("beheergebied1")
            .beheerobjectbeheervak("beheerobjectbeheervak1")
            .beheerobjectgebruiksfunctie("beheerobjectgebruiksfunctie1")
            .beheerobjectmemo("beheerobjectmemo1")
            .buurt("buurt1")
            .conversieid("conversieid1")
            .gebiedstype("gebiedstype1")
            .gemeente("gemeente1")
            .geometrie("geometrie1")
            .gewijzigddoor("gewijzigddoor1")
            .grondsoort("grondsoort1")
            .grondsoortplus("grondsoortplus1")
            .identificatieimbor("identificatieimbor1")
            .identificatieimgeo("identificatieimgeo1")
            .jaarvanaanleg("jaarvanaanleg1")
            .eobjectbegintijd("eobjectbegintijd1")
            .eobjecteindtijd("eobjecteindtijd1")
            .onderhoudsplichtige("onderhoudsplichtige1")
            .openbareruimte("openbareruimte1")
            .postcode("postcode1")
            .relatievehoogteligging("relatievehoogteligging1")
            .stadsdeel("stadsdeel1")
            .status("status1")
            .theoretischeindejaar("theoretischeindejaar1")
            .tijdstipregistratie("tijdstipregistratie1")
            .typebeheerder("typebeheerder1")
            .typebeheerderplus("typebeheerderplus1")
            .typeeigenaar("typeeigenaar1")
            .typeeigenaarplus("typeeigenaarplus1")
            .typeligging("typeligging1")
            .waterschap("waterschap1")
            .wijk("wijk1")
            .woonplaats("woonplaats1")
            .zettingsgevoeligheid("zettingsgevoeligheid1")
            .zettingsgevoeligheidplus("zettingsgevoeligheidplus1");
    }

    public static Beheerobject getBeheerobjectSample2() {
        return new Beheerobject()
            .id(2L)
            .aangemaaktdoor("aangemaaktdoor2")
            .beheergebied("beheergebied2")
            .beheerobjectbeheervak("beheerobjectbeheervak2")
            .beheerobjectgebruiksfunctie("beheerobjectgebruiksfunctie2")
            .beheerobjectmemo("beheerobjectmemo2")
            .buurt("buurt2")
            .conversieid("conversieid2")
            .gebiedstype("gebiedstype2")
            .gemeente("gemeente2")
            .geometrie("geometrie2")
            .gewijzigddoor("gewijzigddoor2")
            .grondsoort("grondsoort2")
            .grondsoortplus("grondsoortplus2")
            .identificatieimbor("identificatieimbor2")
            .identificatieimgeo("identificatieimgeo2")
            .jaarvanaanleg("jaarvanaanleg2")
            .eobjectbegintijd("eobjectbegintijd2")
            .eobjecteindtijd("eobjecteindtijd2")
            .onderhoudsplichtige("onderhoudsplichtige2")
            .openbareruimte("openbareruimte2")
            .postcode("postcode2")
            .relatievehoogteligging("relatievehoogteligging2")
            .stadsdeel("stadsdeel2")
            .status("status2")
            .theoretischeindejaar("theoretischeindejaar2")
            .tijdstipregistratie("tijdstipregistratie2")
            .typebeheerder("typebeheerder2")
            .typebeheerderplus("typebeheerderplus2")
            .typeeigenaar("typeeigenaar2")
            .typeeigenaarplus("typeeigenaarplus2")
            .typeligging("typeligging2")
            .waterschap("waterschap2")
            .wijk("wijk2")
            .woonplaats("woonplaats2")
            .zettingsgevoeligheid("zettingsgevoeligheid2")
            .zettingsgevoeligheidplus("zettingsgevoeligheidplus2");
    }

    public static Beheerobject getBeheerobjectRandomSampleGenerator() {
        return new Beheerobject()
            .id(longCount.incrementAndGet())
            .aangemaaktdoor(UUID.randomUUID().toString())
            .beheergebied(UUID.randomUUID().toString())
            .beheerobjectbeheervak(UUID.randomUUID().toString())
            .beheerobjectgebruiksfunctie(UUID.randomUUID().toString())
            .beheerobjectmemo(UUID.randomUUID().toString())
            .buurt(UUID.randomUUID().toString())
            .conversieid(UUID.randomUUID().toString())
            .gebiedstype(UUID.randomUUID().toString())
            .gemeente(UUID.randomUUID().toString())
            .geometrie(UUID.randomUUID().toString())
            .gewijzigddoor(UUID.randomUUID().toString())
            .grondsoort(UUID.randomUUID().toString())
            .grondsoortplus(UUID.randomUUID().toString())
            .identificatieimbor(UUID.randomUUID().toString())
            .identificatieimgeo(UUID.randomUUID().toString())
            .jaarvanaanleg(UUID.randomUUID().toString())
            .eobjectbegintijd(UUID.randomUUID().toString())
            .eobjecteindtijd(UUID.randomUUID().toString())
            .onderhoudsplichtige(UUID.randomUUID().toString())
            .openbareruimte(UUID.randomUUID().toString())
            .postcode(UUID.randomUUID().toString())
            .relatievehoogteligging(UUID.randomUUID().toString())
            .stadsdeel(UUID.randomUUID().toString())
            .status(UUID.randomUUID().toString())
            .theoretischeindejaar(UUID.randomUUID().toString())
            .tijdstipregistratie(UUID.randomUUID().toString())
            .typebeheerder(UUID.randomUUID().toString())
            .typebeheerderplus(UUID.randomUUID().toString())
            .typeeigenaar(UUID.randomUUID().toString())
            .typeeigenaarplus(UUID.randomUUID().toString())
            .typeligging(UUID.randomUUID().toString())
            .waterschap(UUID.randomUUID().toString())
            .wijk(UUID.randomUUID().toString())
            .woonplaats(UUID.randomUUID().toString())
            .zettingsgevoeligheid(UUID.randomUUID().toString())
            .zettingsgevoeligheidplus(UUID.randomUUID().toString());
    }
}
