package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BeschikkingleerlingenvervoerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBeschikkingleerlingenvervoerAllPropertiesEquals(
        Beschikkingleerlingenvervoer expected,
        Beschikkingleerlingenvervoer actual
    ) {
        assertBeschikkingleerlingenvervoerAutoGeneratedPropertiesEquals(expected, actual);
        assertBeschikkingleerlingenvervoerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBeschikkingleerlingenvervoerAllUpdatablePropertiesEquals(
        Beschikkingleerlingenvervoer expected,
        Beschikkingleerlingenvervoer actual
    ) {
        assertBeschikkingleerlingenvervoerUpdatableFieldsEquals(expected, actual);
        assertBeschikkingleerlingenvervoerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBeschikkingleerlingenvervoerAutoGeneratedPropertiesEquals(
        Beschikkingleerlingenvervoer expected,
        Beschikkingleerlingenvervoer actual
    ) {
        assertThat(expected)
            .as("Verify Beschikkingleerlingenvervoer auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBeschikkingleerlingenvervoerUpdatableFieldsEquals(
        Beschikkingleerlingenvervoer expected,
        Beschikkingleerlingenvervoer actual
    ) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBeschikkingleerlingenvervoerUpdatableRelationshipsEquals(
        Beschikkingleerlingenvervoer expected,
        Beschikkingleerlingenvervoer actual
    ) {}
}
