package nl.ritense.demo.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class BoomTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static Boom getBoomSample1() {
        return new Boom()
            .id(1L)
            .beleidsstatus("beleidsstatus1")
            .beoogdeomlooptijd("beoogdeomlooptijd1")
            .boombeeld("boombeeld1")
            .boombeschermer("boombeschermer1")
            .boomgroep("boomgroep1")
            .boomhoogteactueel("boomhoogteactueel1")
            .boomhoogteklasseactueel("boomhoogteklasseactueel1")
            .boomhoogteklasseeindebeeld("boomhoogteklasseeindebeeld1")
            .boomspiegel("boomspiegel1")
            .boomtypebeschermingsstatusplus("boomtypebeschermingsstatusplus1")
            .boomvoorziening("boomvoorziening1")
            .controlefrequentie("controlefrequentie1")
            .feestverlichting("feestverlichting1")
            .groeifase("groeifase1")
            .groeiplaatsinrichting("groeiplaatsinrichting1")
            .kiemjaar("kiemjaar1")
            .kroondiameterklasseactueel("kroondiameterklasseactueel1")
            .kroondiameterklasseeindebeeld("kroondiameterklasseeindebeeld1")
            .kroonvolume("kroonvolume1")
            .leeftijd("leeftijd1")
            .monetaireboomwaarde("monetaireboomwaarde1")
            .snoeifase("snoeifase1")
            .stamdiameter("stamdiameter1")
            .stamdiameterklasse("stamdiameterklasse1")
            .takvrijeruimtetotgebouw("takvrijeruimtetotgebouw1")
            .takvrijestam("takvrijestam1")
            .takvrijezoneprimair("takvrijezoneprimair1")
            .takvrijezonesecundair("takvrijezonesecundair1")
            .transponder("transponder1")
            .type("type1")
            .typebeschermingsstatus("typebeschermingsstatus1")
            .typeomgevingsrisicoklasse("typeomgevingsrisicoklasse1")
            .typeplus("typeplus1")
            .typevermeerderingsvorm("typevermeerderingsvorm1")
            .veiligheidsklasseboom("veiligheidsklasseboom1")
            .vrijedoorrijhoogte("vrijedoorrijhoogte1")
            .vrijedoorrijhoogteprimair("vrijedoorrijhoogteprimair1")
            .vrijedoorrijhoogtesecundair("vrijedoorrijhoogtesecundair1")
            .vrijetakval("vrijetakval1");
    }

    public static Boom getBoomSample2() {
        return new Boom()
            .id(2L)
            .beleidsstatus("beleidsstatus2")
            .beoogdeomlooptijd("beoogdeomlooptijd2")
            .boombeeld("boombeeld2")
            .boombeschermer("boombeschermer2")
            .boomgroep("boomgroep2")
            .boomhoogteactueel("boomhoogteactueel2")
            .boomhoogteklasseactueel("boomhoogteklasseactueel2")
            .boomhoogteklasseeindebeeld("boomhoogteklasseeindebeeld2")
            .boomspiegel("boomspiegel2")
            .boomtypebeschermingsstatusplus("boomtypebeschermingsstatusplus2")
            .boomvoorziening("boomvoorziening2")
            .controlefrequentie("controlefrequentie2")
            .feestverlichting("feestverlichting2")
            .groeifase("groeifase2")
            .groeiplaatsinrichting("groeiplaatsinrichting2")
            .kiemjaar("kiemjaar2")
            .kroondiameterklasseactueel("kroondiameterklasseactueel2")
            .kroondiameterklasseeindebeeld("kroondiameterklasseeindebeeld2")
            .kroonvolume("kroonvolume2")
            .leeftijd("leeftijd2")
            .monetaireboomwaarde("monetaireboomwaarde2")
            .snoeifase("snoeifase2")
            .stamdiameter("stamdiameter2")
            .stamdiameterklasse("stamdiameterklasse2")
            .takvrijeruimtetotgebouw("takvrijeruimtetotgebouw2")
            .takvrijestam("takvrijestam2")
            .takvrijezoneprimair("takvrijezoneprimair2")
            .takvrijezonesecundair("takvrijezonesecundair2")
            .transponder("transponder2")
            .type("type2")
            .typebeschermingsstatus("typebeschermingsstatus2")
            .typeomgevingsrisicoklasse("typeomgevingsrisicoklasse2")
            .typeplus("typeplus2")
            .typevermeerderingsvorm("typevermeerderingsvorm2")
            .veiligheidsklasseboom("veiligheidsklasseboom2")
            .vrijedoorrijhoogte("vrijedoorrijhoogte2")
            .vrijedoorrijhoogteprimair("vrijedoorrijhoogteprimair2")
            .vrijedoorrijhoogtesecundair("vrijedoorrijhoogtesecundair2")
            .vrijetakval("vrijetakval2");
    }

    public static Boom getBoomRandomSampleGenerator() {
        return new Boom()
            .id(longCount.incrementAndGet())
            .beleidsstatus(UUID.randomUUID().toString())
            .beoogdeomlooptijd(UUID.randomUUID().toString())
            .boombeeld(UUID.randomUUID().toString())
            .boombeschermer(UUID.randomUUID().toString())
            .boomgroep(UUID.randomUUID().toString())
            .boomhoogteactueel(UUID.randomUUID().toString())
            .boomhoogteklasseactueel(UUID.randomUUID().toString())
            .boomhoogteklasseeindebeeld(UUID.randomUUID().toString())
            .boomspiegel(UUID.randomUUID().toString())
            .boomtypebeschermingsstatusplus(UUID.randomUUID().toString())
            .boomvoorziening(UUID.randomUUID().toString())
            .controlefrequentie(UUID.randomUUID().toString())
            .feestverlichting(UUID.randomUUID().toString())
            .groeifase(UUID.randomUUID().toString())
            .groeiplaatsinrichting(UUID.randomUUID().toString())
            .kiemjaar(UUID.randomUUID().toString())
            .kroondiameterklasseactueel(UUID.randomUUID().toString())
            .kroondiameterklasseeindebeeld(UUID.randomUUID().toString())
            .kroonvolume(UUID.randomUUID().toString())
            .leeftijd(UUID.randomUUID().toString())
            .monetaireboomwaarde(UUID.randomUUID().toString())
            .snoeifase(UUID.randomUUID().toString())
            .stamdiameter(UUID.randomUUID().toString())
            .stamdiameterklasse(UUID.randomUUID().toString())
            .takvrijeruimtetotgebouw(UUID.randomUUID().toString())
            .takvrijestam(UUID.randomUUID().toString())
            .takvrijezoneprimair(UUID.randomUUID().toString())
            .takvrijezonesecundair(UUID.randomUUID().toString())
            .transponder(UUID.randomUUID().toString())
            .type(UUID.randomUUID().toString())
            .typebeschermingsstatus(UUID.randomUUID().toString())
            .typeomgevingsrisicoklasse(UUID.randomUUID().toString())
            .typeplus(UUID.randomUUID().toString())
            .typevermeerderingsvorm(UUID.randomUUID().toString())
            .veiligheidsklasseboom(UUID.randomUUID().toString())
            .vrijedoorrijhoogte(UUID.randomUUID().toString())
            .vrijedoorrijhoogteprimair(UUID.randomUUID().toString())
            .vrijedoorrijhoogtesecundair(UUID.randomUUID().toString())
            .vrijetakval(UUID.randomUUID().toString());
    }
}
