package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BouwstijlAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBouwstijlAllPropertiesEquals(Bouwstijl expected, Bouwstijl actual) {
        assertBouwstijlAutoGeneratedPropertiesEquals(expected, actual);
        assertBouwstijlAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBouwstijlAllUpdatablePropertiesEquals(Bouwstijl expected, Bouwstijl actual) {
        assertBouwstijlUpdatableFieldsEquals(expected, actual);
        assertBouwstijlUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBouwstijlAutoGeneratedPropertiesEquals(Bouwstijl expected, Bouwstijl actual) {
        assertThat(expected)
            .as("Verify Bouwstijl auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBouwstijlUpdatableFieldsEquals(Bouwstijl expected, Bouwstijl actual) {
        assertThat(expected)
            .as("Verify Bouwstijl relevant properties")
            .satisfies(e -> assertThat(e.getHoofdstijl()).as("check hoofdstijl").isEqualTo(actual.getHoofdstijl()))
            .satisfies(e -> assertThat(e.getSubstijl()).as("check substijl").isEqualTo(actual.getSubstijl()))
            .satisfies(e -> assertThat(e.getToelichting()).as("check toelichting").isEqualTo(actual.getToelichting()))
            .satisfies(e -> assertThat(e.getZuiverheid()).as("check zuiverheid").isEqualTo(actual.getZuiverheid()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBouwstijlUpdatableRelationshipsEquals(Bouwstijl expected, Bouwstijl actual) {}
}
