package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChildclassaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChildclassaAllPropertiesEquals(Childclassa expected, Childclassa actual) {
        assertChildclassaAutoGeneratedPropertiesEquals(expected, actual);
        assertChildclassaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChildclassaAllUpdatablePropertiesEquals(Childclassa expected, Childclassa actual) {
        assertChildclassaUpdatableFieldsEquals(expected, actual);
        assertChildclassaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChildclassaAutoGeneratedPropertiesEquals(Childclassa expected, Childclassa actual) {
        assertThat(expected)
            .as("Verify Childclassa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChildclassaUpdatableFieldsEquals(Childclassa expected, Childclassa actual) {
        assertThat(expected)
            .as("Verify Childclassa relevant properties")
            .satisfies(e -> assertThat(e.getKleur()).as("check kleur").isEqualTo(actual.getKleur()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChildclassaUpdatableRelationshipsEquals(Childclassa expected, Childclassa actual) {}
}
