package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassiAllPropertiesEquals(Classi expected, Classi actual) {
        assertClassiAutoGeneratedPropertiesEquals(expected, actual);
        assertClassiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassiAllUpdatablePropertiesEquals(Classi expected, Classi actual) {
        assertClassiUpdatableFieldsEquals(expected, actual);
        assertClassiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassiAutoGeneratedPropertiesEquals(Classi expected, Classi actual) {
        assertThat(expected)
            .as("Verify Classi auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassiUpdatableFieldsEquals(Classi expected, Classi actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassiUpdatableRelationshipsEquals(Classi expected, Classi actual) {}
}
