package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeelplanveldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeelplanveldAllPropertiesEquals(Deelplanveld expected, Deelplanveld actual) {
        assertDeelplanveldAutoGeneratedPropertiesEquals(expected, actual);
        assertDeelplanveldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeelplanveldAllUpdatablePropertiesEquals(Deelplanveld expected, Deelplanveld actual) {
        assertDeelplanveldUpdatableFieldsEquals(expected, actual);
        assertDeelplanveldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeelplanveldAutoGeneratedPropertiesEquals(Deelplanveld expected, Deelplanveld actual) {
        assertThat(expected)
            .as("Verify Deelplanveld auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeelplanveldUpdatableFieldsEquals(Deelplanveld expected, Deelplanveld actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeelplanveldUpdatableRelationshipsEquals(Deelplanveld expected, Deelplanveld actual) {}
}
