package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoelstellingsoortAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoelstellingsoortAllPropertiesEquals(Doelstellingsoort expected, Doelstellingsoort actual) {
        assertDoelstellingsoortAutoGeneratedPropertiesEquals(expected, actual);
        assertDoelstellingsoortAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoelstellingsoortAllUpdatablePropertiesEquals(Doelstellingsoort expected, Doelstellingsoort actual) {
        assertDoelstellingsoortUpdatableFieldsEquals(expected, actual);
        assertDoelstellingsoortUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoelstellingsoortAutoGeneratedPropertiesEquals(Doelstellingsoort expected, Doelstellingsoort actual) {
        assertThat(expected)
            .as("Verify Doelstellingsoort auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoelstellingsoortUpdatableFieldsEquals(Doelstellingsoort expected, Doelstellingsoort actual) {
        assertThat(expected)
            .as("Verify Doelstellingsoort relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoelstellingsoortUpdatableRelationshipsEquals(Doelstellingsoort expected, Doelstellingsoort actual) {}
}
