package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EcoductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcoductAllPropertiesEquals(Ecoduct expected, Ecoduct actual) {
        assertEcoductAutoGeneratedPropertiesEquals(expected, actual);
        assertEcoductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcoductAllUpdatablePropertiesEquals(Ecoduct expected, Ecoduct actual) {
        assertEcoductUpdatableFieldsEquals(expected, actual);
        assertEcoductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcoductAutoGeneratedPropertiesEquals(Ecoduct expected, Ecoduct actual) {
        assertThat(expected)
            .as("Verify Ecoduct auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcoductUpdatableFieldsEquals(Ecoduct expected, Ecoduct actual) {
        assertThat(expected)
            .as("Verify Ecoduct relevant properties")
            .satisfies(
                e -> assertThat(e.getAantaloverspanningen()).as("check aantaloverspanningen").isEqualTo(actual.getAantaloverspanningen())
            )
            .satisfies(e -> assertThat(e.getDraagvermogen()).as("check draagvermogen").isEqualTo(actual.getDraagvermogen()))
            .satisfies(
                e ->
                    assertThat(e.getMaximaaltoelaatbaarvoertuiggewicht())
                        .as("check maximaaltoelaatbaarvoertuiggewicht")
                        .isEqualTo(actual.getMaximaaltoelaatbaarvoertuiggewicht())
            )
            .satisfies(
                e -> assertThat(e.getMaximaleasbelasting()).as("check maximaleasbelasting").isEqualTo(actual.getMaximaleasbelasting())
            )
            .satisfies(
                e -> assertThat(e.getMaximaleoverspanning()).as("check maximaleoverspanning").isEqualTo(actual.getMaximaleoverspanning())
            )
            .satisfies(
                e ->
                    assertThat(e.getOverbruggingsobjectdoorrijopening())
                        .as("check overbruggingsobjectdoorrijopening")
                        .isEqualTo(actual.getOverbruggingsobjectdoorrijopening())
            )
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getZwaarstevoertuig()).as("check zwaarstevoertuig").isEqualTo(actual.getZwaarstevoertuig()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcoductUpdatableRelationshipsEquals(Ecoduct expected, Ecoduct actual) {}
}
