package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GeoobjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoobjectAllPropertiesEquals(Geoobject expected, Geoobject actual) {
        assertGeoobjectAutoGeneratedPropertiesEquals(expected, actual);
        assertGeoobjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoobjectAllUpdatablePropertiesEquals(Geoobject expected, Geoobject actual) {
        assertGeoobjectUpdatableFieldsEquals(expected, actual);
        assertGeoobjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoobjectAutoGeneratedPropertiesEquals(Geoobject expected, Geoobject actual) {
        assertThat(expected)
            .as("Verify Geoobject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoobjectUpdatableFieldsEquals(Geoobject expected, Geoobject actual) {
        assertThat(expected)
            .as("Verify Geoobject relevant properties")
            .satisfies(
                e -> assertThat(e.getDatumbegingeldigheid()).as("check datumbegingeldigheid").isEqualTo(actual.getDatumbegingeldigheid())
            )
            .satisfies(
                e -> assertThat(e.getDatumeindegeldigheid()).as("check datumeindegeldigheid").isEqualTo(actual.getDatumeindegeldigheid())
            )
            .satisfies(e -> assertThat(e.getGeometriesoort()).as("check geometriesoort").isEqualTo(actual.getGeometriesoort()))
            .satisfies(e -> assertThat(e.getIdentificatie()).as("check identificatie").isEqualTo(actual.getIdentificatie()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGeoobjectUpdatableRelationshipsEquals(Geoobject expected, Geoobject actual) {}
}
