package nl.ritense.demo.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class GroenobjectTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static Groenobject getGroenobjectSample1() {
        return new Groenobject()
            .id(1L)
            .aantalobstakels("aantalobstakels1")
            .aantalzijden("aantalzijden1")
            .bereikbaarheid("bereikbaarheid1")
            .bergendvermogen("bergendvermogen1")
            .bewerkingspercentage("bewerkingspercentage1")
            .bgtfysiekvoorkomen("bgtfysiekvoorkomen1")
            .breedte("breedte1")
            .breedteklassehaag("breedteklassehaag1")
            .cultuurhistorischwaardevol("cultuurhistorischwaardevol1")
            .fysiekvoorkomenimgeo("fysiekvoorkomenimgeo1")
            .gewenstsluitingspercentage("gewenstsluitingspercentage1")
            .groenobjectbereikbaarheidplus("groenobjectbereikbaarheidplus1")
            .groenobjectconstructielaag("groenobjectconstructielaag1")
            .groenobjectrand("groenobjectrand1")
            .groenobjectsoortnaam("groenobjectsoortnaam1")
            .haagvoetlengte("haagvoetlengte1")
            .haagvoetoppervlakte("haagvoetoppervlakte1")
            .hoogte("hoogte1")
            .hoogteklassehaag("hoogteklassehaag1")
            .knipfrequentie("knipfrequentie1")
            .knipoppervlakte("knipoppervlakte1")
            .kwaliteitsniveauactueel("kwaliteitsniveauactueel1")
            .kwaliteitsniveaugewenst("kwaliteitsniveaugewenst1")
            .lengte("lengte1")
            .leverancier("leverancier1")
            .maaifrequentie("maaifrequentie1")
            .maximalevalhoogte("maximalevalhoogte1")
            .eobjectnummer("eobjectnummer1")
            .omtrek("omtrek1")
            .ondergroei("ondergroei1")
            .oppervlakte("oppervlakte1")
            .optalud("optalud1")
            .taludsteilte("taludsteilte1")
            .type("type1")
            .typebewerking("typebewerking1")
            .typeomgevingsrisicoklasse("typeomgevingsrisicoklasse1")
            .typeplus("typeplus1")
            .typeplus2("typeplus21")
            .veiligheidsklasseboom("veiligheidsklasseboom1");
    }

    public static Groenobject getGroenobjectSample2() {
        return new Groenobject()
            .id(2L)
            .aantalobstakels("aantalobstakels2")
            .aantalzijden("aantalzijden2")
            .bereikbaarheid("bereikbaarheid2")
            .bergendvermogen("bergendvermogen2")
            .bewerkingspercentage("bewerkingspercentage2")
            .bgtfysiekvoorkomen("bgtfysiekvoorkomen2")
            .breedte("breedte2")
            .breedteklassehaag("breedteklassehaag2")
            .cultuurhistorischwaardevol("cultuurhistorischwaardevol2")
            .fysiekvoorkomenimgeo("fysiekvoorkomenimgeo2")
            .gewenstsluitingspercentage("gewenstsluitingspercentage2")
            .groenobjectbereikbaarheidplus("groenobjectbereikbaarheidplus2")
            .groenobjectconstructielaag("groenobjectconstructielaag2")
            .groenobjectrand("groenobjectrand2")
            .groenobjectsoortnaam("groenobjectsoortnaam2")
            .haagvoetlengte("haagvoetlengte2")
            .haagvoetoppervlakte("haagvoetoppervlakte2")
            .hoogte("hoogte2")
            .hoogteklassehaag("hoogteklassehaag2")
            .knipfrequentie("knipfrequentie2")
            .knipoppervlakte("knipoppervlakte2")
            .kwaliteitsniveauactueel("kwaliteitsniveauactueel2")
            .kwaliteitsniveaugewenst("kwaliteitsniveaugewenst2")
            .lengte("lengte2")
            .leverancier("leverancier2")
            .maaifrequentie("maaifrequentie2")
            .maximalevalhoogte("maximalevalhoogte2")
            .eobjectnummer("eobjectnummer2")
            .omtrek("omtrek2")
            .ondergroei("ondergroei2")
            .oppervlakte("oppervlakte2")
            .optalud("optalud2")
            .taludsteilte("taludsteilte2")
            .type("type2")
            .typebewerking("typebewerking2")
            .typeomgevingsrisicoklasse("typeomgevingsrisicoklasse2")
            .typeplus("typeplus2")
            .typeplus2("typeplus22")
            .veiligheidsklasseboom("veiligheidsklasseboom2");
    }

    public static Groenobject getGroenobjectRandomSampleGenerator() {
        return new Groenobject()
            .id(longCount.incrementAndGet())
            .aantalobstakels(UUID.randomUUID().toString())
            .aantalzijden(UUID.randomUUID().toString())
            .bereikbaarheid(UUID.randomUUID().toString())
            .bergendvermogen(UUID.randomUUID().toString())
            .bewerkingspercentage(UUID.randomUUID().toString())
            .bgtfysiekvoorkomen(UUID.randomUUID().toString())
            .breedte(UUID.randomUUID().toString())
            .breedteklassehaag(UUID.randomUUID().toString())
            .cultuurhistorischwaardevol(UUID.randomUUID().toString())
            .fysiekvoorkomenimgeo(UUID.randomUUID().toString())
            .gewenstsluitingspercentage(UUID.randomUUID().toString())
            .groenobjectbereikbaarheidplus(UUID.randomUUID().toString())
            .groenobjectconstructielaag(UUID.randomUUID().toString())
            .groenobjectrand(UUID.randomUUID().toString())
            .groenobjectsoortnaam(UUID.randomUUID().toString())
            .haagvoetlengte(UUID.randomUUID().toString())
            .haagvoetoppervlakte(UUID.randomUUID().toString())
            .hoogte(UUID.randomUUID().toString())
            .hoogteklassehaag(UUID.randomUUID().toString())
            .knipfrequentie(UUID.randomUUID().toString())
            .knipoppervlakte(UUID.randomUUID().toString())
            .kwaliteitsniveauactueel(UUID.randomUUID().toString())
            .kwaliteitsniveaugewenst(UUID.randomUUID().toString())
            .lengte(UUID.randomUUID().toString())
            .leverancier(UUID.randomUUID().toString())
            .maaifrequentie(UUID.randomUUID().toString())
            .maximalevalhoogte(UUID.randomUUID().toString())
            .eobjectnummer(UUID.randomUUID().toString())
            .omtrek(UUID.randomUUID().toString())
            .ondergroei(UUID.randomUUID().toString())
            .oppervlakte(UUID.randomUUID().toString())
            .optalud(UUID.randomUUID().toString())
            .taludsteilte(UUID.randomUUID().toString())
            .type(UUID.randomUUID().toString())
            .typebewerking(UUID.randomUUID().toString())
            .typeomgevingsrisicoklasse(UUID.randomUUID().toString())
            .typeplus(UUID.randomUUID().toString())
            .typeplus2(UUID.randomUUID().toString())
            .veiligheidsklasseboom(UUID.randomUUID().toString());
    }
}
