package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HardwareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareAllPropertiesEquals(Hardware expected, Hardware actual) {
        assertHardwareAutoGeneratedPropertiesEquals(expected, actual);
        assertHardwareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareAllUpdatablePropertiesEquals(Hardware expected, Hardware actual) {
        assertHardwareUpdatableFieldsEquals(expected, actual);
        assertHardwareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareAutoGeneratedPropertiesEquals(Hardware expected, Hardware actual) {
        assertThat(expected)
            .as("Verify Hardware auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareUpdatableFieldsEquals(Hardware expected, Hardware actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHardwareUpdatableRelationshipsEquals(Hardware expected, Hardware actual) {}
}
