package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistorischerolAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorischerolAllPropertiesEquals(Historischerol expected, Historischerol actual) {
        assertHistorischerolAutoGeneratedPropertiesEquals(expected, actual);
        assertHistorischerolAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorischerolAllUpdatablePropertiesEquals(Historischerol expected, Historischerol actual) {
        assertHistorischerolUpdatableFieldsEquals(expected, actual);
        assertHistorischerolUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorischerolAutoGeneratedPropertiesEquals(Historischerol expected, Historischerol actual) {
        assertThat(expected)
            .as("Verify Historischerol auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorischerolUpdatableFieldsEquals(Historischerol expected, Historischerol actual) {
        assertThat(expected)
            .as("Verify Historischerol relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistorischerolUpdatableRelationshipsEquals(Historischerol expected, Historischerol actual) {}
}
