package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InburgeringstrajectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInburgeringstrajectAllPropertiesEquals(Inburgeringstraject expected, Inburgeringstraject actual) {
        assertInburgeringstrajectAutoGeneratedPropertiesEquals(expected, actual);
        assertInburgeringstrajectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInburgeringstrajectAllUpdatablePropertiesEquals(Inburgeringstraject expected, Inburgeringstraject actual) {
        assertInburgeringstrajectUpdatableFieldsEquals(expected, actual);
        assertInburgeringstrajectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInburgeringstrajectAutoGeneratedPropertiesEquals(Inburgeringstraject expected, Inburgeringstraject actual) {
        assertThat(expected)
            .as("Verify Inburgeringstraject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInburgeringstrajectUpdatableFieldsEquals(Inburgeringstraject expected, Inburgeringstraject actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInburgeringstrajectUpdatableRelationshipsEquals(Inburgeringstraject expected, Inburgeringstraject actual) {}
}
