package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndexAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexAllPropertiesEquals(Index expected, Index actual) {
        assertIndexAutoGeneratedPropertiesEquals(expected, actual);
        assertIndexAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexAllUpdatablePropertiesEquals(Index expected, Index actual) {
        assertIndexUpdatableFieldsEquals(expected, actual);
        assertIndexUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexAutoGeneratedPropertiesEquals(Index expected, Index actual) {
        assertThat(expected)
            .as("Verify Index auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexUpdatableFieldsEquals(Index expected, Index actual) {
        assertThat(expected)
            .as("Verify Index relevant properties")
            .satisfies(e -> assertThat(e.getIndexnaam()).as("check indexnaam").isEqualTo(actual.getIndexnaam()))
            .satisfies(e -> assertThat(e.getIndexwaarde()).as("check indexwaarde").isEqualTo(actual.getIndexwaarde()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexUpdatableRelationshipsEquals(Index expected, Index actual) {}
}
