package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndieningsvereistenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndieningsvereistenAllPropertiesEquals(Indieningsvereisten expected, Indieningsvereisten actual) {
        assertIndieningsvereistenAutoGeneratedPropertiesEquals(expected, actual);
        assertIndieningsvereistenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndieningsvereistenAllUpdatablePropertiesEquals(Indieningsvereisten expected, Indieningsvereisten actual) {
        assertIndieningsvereistenUpdatableFieldsEquals(expected, actual);
        assertIndieningsvereistenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndieningsvereistenAutoGeneratedPropertiesEquals(Indieningsvereisten expected, Indieningsvereisten actual) {
        assertThat(expected)
            .as("Verify Indieningsvereisten auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndieningsvereistenUpdatableFieldsEquals(Indieningsvereisten expected, Indieningsvereisten actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndieningsvereistenUpdatableRelationshipsEquals(Indieningsvereisten expected, Indieningsvereisten actual) {}
}
