package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InkooppakketAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInkooppakketAllPropertiesEquals(Inkooppakket expected, Inkooppakket actual) {
        assertInkooppakketAutoGeneratedPropertiesEquals(expected, actual);
        assertInkooppakketAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInkooppakketAllUpdatablePropertiesEquals(Inkooppakket expected, Inkooppakket actual) {
        assertInkooppakketUpdatableFieldsEquals(expected, actual);
        assertInkooppakketUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInkooppakketAutoGeneratedPropertiesEquals(Inkooppakket expected, Inkooppakket actual) {
        assertThat(expected)
            .as("Verify Inkooppakket auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInkooppakketUpdatableFieldsEquals(Inkooppakket expected, Inkooppakket actual) {
        assertThat(expected)
            .as("Verify Inkooppakket relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInkooppakketUpdatableRelationshipsEquals(Inkooppakket expected, Inkooppakket actual) {}
}
