package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventarisAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarisAllPropertiesEquals(Inventaris expected, Inventaris actual) {
        assertInventarisAutoGeneratedPropertiesEquals(expected, actual);
        assertInventarisAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarisAllUpdatablePropertiesEquals(Inventaris expected, Inventaris actual) {
        assertInventarisUpdatableFieldsEquals(expected, actual);
        assertInventarisUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarisAutoGeneratedPropertiesEquals(Inventaris expected, Inventaris actual) {
        assertThat(expected)
            .as("Verify Inventaris auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarisUpdatableFieldsEquals(Inventaris expected, Inventaris actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarisUpdatableRelationshipsEquals(Inventaris expected, Inventaris actual) {}
}
