package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KadastraleonroerendezaakaantekeningAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKadastraleonroerendezaakaantekeningAllPropertiesEquals(
        Kadastraleonroerendezaakaantekening expected,
        Kadastraleonroerendezaakaantekening actual
    ) {
        assertKadastraleonroerendezaakaantekeningAutoGeneratedPropertiesEquals(expected, actual);
        assertKadastraleonroerendezaakaantekeningAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKadastraleonroerendezaakaantekeningAllUpdatablePropertiesEquals(
        Kadastraleonroerendezaakaantekening expected,
        Kadastraleonroerendezaakaantekening actual
    ) {
        assertKadastraleonroerendezaakaantekeningUpdatableFieldsEquals(expected, actual);
        assertKadastraleonroerendezaakaantekeningUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKadastraleonroerendezaakaantekeningAutoGeneratedPropertiesEquals(
        Kadastraleonroerendezaakaantekening expected,
        Kadastraleonroerendezaakaantekening actual
    ) {
        assertThat(expected)
            .as("Verify Kadastraleonroerendezaakaantekening auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKadastraleonroerendezaakaantekeningUpdatableFieldsEquals(
        Kadastraleonroerendezaakaantekening expected,
        Kadastraleonroerendezaakaantekening actual
    ) {
        assertThat(expected)
            .as("Verify Kadastraleonroerendezaakaantekening relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getAardaantekeningkadastraalobject())
                        .as("check aardaantekeningkadastraalobject")
                        .isEqualTo(actual.getAardaantekeningkadastraalobject())
            )
            .satisfies(
                e ->
                    assertThat(e.getBeschrijvingaantekeningkadastraalobject())
                        .as("check beschrijvingaantekeningkadastraalobject")
                        .isEqualTo(actual.getBeschrijvingaantekeningkadastraalobject())
            )
            .satisfies(
                e ->
                    assertThat(e.getDatumbeginaantekeningkadastraalobject())
                        .as("check datumbeginaantekeningkadastraalobject")
                        .isEqualTo(actual.getDatumbeginaantekeningkadastraalobject())
            )
            .satisfies(
                e ->
                    assertThat(e.getDatumeindeaantekeningkadastraalobject())
                        .as("check datumeindeaantekeningkadastraalobject")
                        .isEqualTo(actual.getDatumeindeaantekeningkadastraalobject())
            )
            .satisfies(
                e ->
                    assertThat(e.getKadasteridentificatieaantekening())
                        .as("check kadasteridentificatieaantekening")
                        .isEqualTo(actual.getKadasteridentificatieaantekening())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKadastraleonroerendezaakaantekeningUpdatableRelationshipsEquals(
        Kadastraleonroerendezaakaantekening expected,
        Kadastraleonroerendezaakaantekening actual
    ) {}
}
