package nl.ritense.demo.domain;

import static nl.ritense.demo.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class KeuzebudgetbestedingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeuzebudgetbestedingAllPropertiesEquals(Keuzebudgetbesteding expected, Keuzebudgetbesteding actual) {
        assertKeuzebudgetbestedingAutoGeneratedPropertiesEquals(expected, actual);
        assertKeuzebudgetbestedingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeuzebudgetbestedingAllUpdatablePropertiesEquals(Keuzebudgetbesteding expected, Keuzebudgetbesteding actual) {
        assertKeuzebudgetbestedingUpdatableFieldsEquals(expected, actual);
        assertKeuzebudgetbestedingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeuzebudgetbestedingAutoGeneratedPropertiesEquals(Keuzebudgetbesteding expected, Keuzebudgetbesteding actual) {
        assertThat(expected)
            .as("Verify Keuzebudgetbesteding auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeuzebudgetbestedingUpdatableFieldsEquals(Keuzebudgetbesteding expected, Keuzebudgetbesteding actual) {
        assertThat(expected)
            .as("Verify Keuzebudgetbesteding relevant properties")
            .satisfies(e -> assertThat(e.getBedrag()).as("check bedrag").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getBedrag()))
            .satisfies(e -> assertThat(e.getDatum()).as("check datum").isEqualTo(actual.getDatum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeuzebudgetbestedingUpdatableRelationshipsEquals(Keuzebudgetbesteding expected, Keuzebudgetbesteding actual) {}
}
