package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LeerplichtambtenaarAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeerplichtambtenaarAllPropertiesEquals(Leerplichtambtenaar expected, Leerplichtambtenaar actual) {
        assertLeerplichtambtenaarAutoGeneratedPropertiesEquals(expected, actual);
        assertLeerplichtambtenaarAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeerplichtambtenaarAllUpdatablePropertiesEquals(Leerplichtambtenaar expected, Leerplichtambtenaar actual) {
        assertLeerplichtambtenaarUpdatableFieldsEquals(expected, actual);
        assertLeerplichtambtenaarUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeerplichtambtenaarAutoGeneratedPropertiesEquals(Leerplichtambtenaar expected, Leerplichtambtenaar actual) {
        assertThat(expected)
            .as("Verify Leerplichtambtenaar auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeerplichtambtenaarUpdatableFieldsEquals(Leerplichtambtenaar expected, Leerplichtambtenaar actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLeerplichtambtenaarUpdatableRelationshipsEquals(Leerplichtambtenaar expected, Leerplichtambtenaar actual) {}
}
