package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LigplaatsontheffingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigplaatsontheffingAllPropertiesEquals(Ligplaatsontheffing expected, Ligplaatsontheffing actual) {
        assertLigplaatsontheffingAutoGeneratedPropertiesEquals(expected, actual);
        assertLigplaatsontheffingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigplaatsontheffingAllUpdatablePropertiesEquals(Ligplaatsontheffing expected, Ligplaatsontheffing actual) {
        assertLigplaatsontheffingUpdatableFieldsEquals(expected, actual);
        assertLigplaatsontheffingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigplaatsontheffingAutoGeneratedPropertiesEquals(Ligplaatsontheffing expected, Ligplaatsontheffing actual) {
        assertThat(expected)
            .as("Verify Ligplaatsontheffing auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigplaatsontheffingUpdatableFieldsEquals(Ligplaatsontheffing expected, Ligplaatsontheffing actual) {
        assertThat(expected)
            .as("Verify Ligplaatsontheffing relevant properties")
            .satisfies(e -> assertThat(e.getStickernummer()).as("check stickernummer").isEqualTo(actual.getStickernummer()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigplaatsontheffingUpdatableRelationshipsEquals(Ligplaatsontheffing expected, Ligplaatsontheffing actual) {}
}
