package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NadaanvullingbrpAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNadaanvullingbrpAllPropertiesEquals(Nadaanvullingbrp expected, Nadaanvullingbrp actual) {
        assertNadaanvullingbrpAutoGeneratedPropertiesEquals(expected, actual);
        assertNadaanvullingbrpAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNadaanvullingbrpAllUpdatablePropertiesEquals(Nadaanvullingbrp expected, Nadaanvullingbrp actual) {
        assertNadaanvullingbrpUpdatableFieldsEquals(expected, actual);
        assertNadaanvullingbrpUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNadaanvullingbrpAutoGeneratedPropertiesEquals(Nadaanvullingbrp expected, Nadaanvullingbrp actual) {
        assertThat(expected)
            .as("Verify Nadaanvullingbrp auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNadaanvullingbrpUpdatableFieldsEquals(Nadaanvullingbrp expected, Nadaanvullingbrp actual) {
        assertThat(expected)
            .as("Verify Nadaanvullingbrp relevant properties")
            .satisfies(e -> assertThat(e.getOpmerkingen()).as("check opmerkingen").isEqualTo(actual.getOpmerkingen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNadaanvullingbrpUpdatableRelationshipsEquals(Nadaanvullingbrp expected, Nadaanvullingbrp actual) {}
}
