package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OntbindinghuwelijkgeregistreerdpartnerschapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOntbindinghuwelijkgeregistreerdpartnerschapAllPropertiesEquals(
        Ontbindinghuwelijkgeregistreerdpartnerschap expected,
        Ontbindinghuwelijkgeregistreerdpartnerschap actual
    ) {
        assertOntbindinghuwelijkgeregistreerdpartnerschapAutoGeneratedPropertiesEquals(expected, actual);
        assertOntbindinghuwelijkgeregistreerdpartnerschapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOntbindinghuwelijkgeregistreerdpartnerschapAllUpdatablePropertiesEquals(
        Ontbindinghuwelijkgeregistreerdpartnerschap expected,
        Ontbindinghuwelijkgeregistreerdpartnerschap actual
    ) {
        assertOntbindinghuwelijkgeregistreerdpartnerschapUpdatableFieldsEquals(expected, actual);
        assertOntbindinghuwelijkgeregistreerdpartnerschapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOntbindinghuwelijkgeregistreerdpartnerschapAutoGeneratedPropertiesEquals(
        Ontbindinghuwelijkgeregistreerdpartnerschap expected,
        Ontbindinghuwelijkgeregistreerdpartnerschap actual
    ) {
        assertThat(expected)
            .as("Verify Ontbindinghuwelijkgeregistreerdpartnerschap auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOntbindinghuwelijkgeregistreerdpartnerschapUpdatableFieldsEquals(
        Ontbindinghuwelijkgeregistreerdpartnerschap expected,
        Ontbindinghuwelijkgeregistreerdpartnerschap actual
    ) {
        assertThat(expected)
            .as("Verify Ontbindinghuwelijkgeregistreerdpartnerschap relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getBuitenlandseplaatseinde())
                        .as("check buitenlandseplaatseinde")
                        .isEqualTo(actual.getBuitenlandseplaatseinde())
            )
            .satisfies(
                e ->
                    assertThat(e.getBuitenlandseregioeinde())
                        .as("check buitenlandseregioeinde")
                        .isEqualTo(actual.getBuitenlandseregioeinde())
            )
            .satisfies(e -> assertThat(e.getDatumeinde()).as("check datumeinde").isEqualTo(actual.getDatumeinde()))
            .satisfies(e -> assertThat(e.getGemeenteeinde()).as("check gemeenteeinde").isEqualTo(actual.getGemeenteeinde()))
            .satisfies(e -> assertThat(e.getLandofgebiedeinde()).as("check landofgebiedeinde").isEqualTo(actual.getLandofgebiedeinde()))
            .satisfies(
                e ->
                    assertThat(e.getOmschrijvinglocatieeinde())
                        .as("check omschrijvinglocatieeinde")
                        .isEqualTo(actual.getOmschrijvinglocatieeinde())
            )
            .satisfies(e -> assertThat(e.getRedeneinde()).as("check redeneinde").isEqualTo(actual.getRedeneinde()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOntbindinghuwelijkgeregistreerdpartnerschapUpdatableRelationshipsEquals(
        Ontbindinghuwelijkgeregistreerdpartnerschap expected,
        Ontbindinghuwelijkgeregistreerdpartnerschap actual
    ) {}
}
