package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OverigeadresseerbaarobjectaanduidingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOverigeadresseerbaarobjectaanduidingAllPropertiesEquals(
        Overigeadresseerbaarobjectaanduiding expected,
        Overigeadresseerbaarobjectaanduiding actual
    ) {
        assertOverigeadresseerbaarobjectaanduidingAutoGeneratedPropertiesEquals(expected, actual);
        assertOverigeadresseerbaarobjectaanduidingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOverigeadresseerbaarobjectaanduidingAllUpdatablePropertiesEquals(
        Overigeadresseerbaarobjectaanduiding expected,
        Overigeadresseerbaarobjectaanduiding actual
    ) {
        assertOverigeadresseerbaarobjectaanduidingUpdatableFieldsEquals(expected, actual);
        assertOverigeadresseerbaarobjectaanduidingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOverigeadresseerbaarobjectaanduidingAutoGeneratedPropertiesEquals(
        Overigeadresseerbaarobjectaanduiding expected,
        Overigeadresseerbaarobjectaanduiding actual
    ) {
        assertThat(expected)
            .as("Verify Overigeadresseerbaarobjectaanduiding auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOverigeadresseerbaarobjectaanduidingUpdatableFieldsEquals(
        Overigeadresseerbaarobjectaanduiding expected,
        Overigeadresseerbaarobjectaanduiding actual
    ) {
        assertThat(expected)
            .as("Verify Overigeadresseerbaarobjectaanduiding relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getIdentificatiecodeoverigadresseerbaarobjectaanduiding())
                        .as("check identificatiecodeoverigadresseerbaarobjectaanduiding")
                        .isEqualTo(actual.getIdentificatiecodeoverigadresseerbaarobjectaanduiding())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOverigeadresseerbaarobjectaanduidingUpdatableRelationshipsEquals(
        Overigeadresseerbaarobjectaanduiding expected,
        Overigeadresseerbaarobjectaanduiding actual
    ) {}
}
