package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParkeergarageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkeergarageAllPropertiesEquals(Parkeergarage expected, Parkeergarage actual) {
        assertParkeergarageAutoGeneratedPropertiesEquals(expected, actual);
        assertParkeergarageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkeergarageAllUpdatablePropertiesEquals(Parkeergarage expected, Parkeergarage actual) {
        assertParkeergarageUpdatableFieldsEquals(expected, actual);
        assertParkeergarageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkeergarageAutoGeneratedPropertiesEquals(Parkeergarage expected, Parkeergarage actual) {
        assertThat(expected)
            .as("Verify Parkeergarage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkeergarageUpdatableFieldsEquals(Parkeergarage expected, Parkeergarage actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParkeergarageUpdatableRelationshipsEquals(Parkeergarage expected, Parkeergarage actual) {}
}
