package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RegelvooriedereenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegelvooriedereenAllPropertiesEquals(Regelvooriedereen expected, Regelvooriedereen actual) {
        assertRegelvooriedereenAutoGeneratedPropertiesEquals(expected, actual);
        assertRegelvooriedereenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegelvooriedereenAllUpdatablePropertiesEquals(Regelvooriedereen expected, Regelvooriedereen actual) {
        assertRegelvooriedereenUpdatableFieldsEquals(expected, actual);
        assertRegelvooriedereenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegelvooriedereenAutoGeneratedPropertiesEquals(Regelvooriedereen expected, Regelvooriedereen actual) {
        assertThat(expected)
            .as("Verify Regelvooriedereen auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegelvooriedereenUpdatableFieldsEquals(Regelvooriedereen expected, Regelvooriedereen actual) {
        assertThat(expected)
            .as("Verify Regelvooriedereen relevant properties")
            .satisfies(
                e ->
                    assertThat(e.getActiviteitregelkwalificatie())
                        .as("check activiteitregelkwalificatie")
                        .isEqualTo(actual.getActiviteitregelkwalificatie())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegelvooriedereenUpdatableRelationshipsEquals(Regelvooriedereen expected, Regelvooriedereen actual) {}
}
