package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SoortdisciplinairemaatregelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoortdisciplinairemaatregelAllPropertiesEquals(
        Soortdisciplinairemaatregel expected,
        Soortdisciplinairemaatregel actual
    ) {
        assertSoortdisciplinairemaatregelAutoGeneratedPropertiesEquals(expected, actual);
        assertSoortdisciplinairemaatregelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoortdisciplinairemaatregelAllUpdatablePropertiesEquals(
        Soortdisciplinairemaatregel expected,
        Soortdisciplinairemaatregel actual
    ) {
        assertSoortdisciplinairemaatregelUpdatableFieldsEquals(expected, actual);
        assertSoortdisciplinairemaatregelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoortdisciplinairemaatregelAutoGeneratedPropertiesEquals(
        Soortdisciplinairemaatregel expected,
        Soortdisciplinairemaatregel actual
    ) {
        assertThat(expected)
            .as("Verify Soortdisciplinairemaatregel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoortdisciplinairemaatregelUpdatableFieldsEquals(
        Soortdisciplinairemaatregel expected,
        Soortdisciplinairemaatregel actual
    ) {
        assertThat(expected)
            .as("Verify Soortdisciplinairemaatregel relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoortdisciplinairemaatregelUpdatableRelationshipsEquals(
        Soortdisciplinairemaatregel expected,
        Soortdisciplinairemaatregel actual
    ) {}
}
