package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusAllPropertiesEquals(Status expected, Status actual) {
        assertStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusAllUpdatablePropertiesEquals(Status expected, Status actual) {
        assertStatusUpdatableFieldsEquals(expected, actual);
        assertStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusAutoGeneratedPropertiesEquals(Status expected, Status actual) {
        assertThat(expected)
            .as("Verify Status auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusUpdatableFieldsEquals(Status expected, Status actual) {
        assertThat(expected)
            .as("Verify Status relevant properties")
            .satisfies(e -> assertThat(e.getDatumstatusgezet()).as("check datumstatusgezet").isEqualTo(actual.getDatumstatusgezet()))
            .satisfies(
                e ->
                    assertThat(e.getIndicatieiaatstgezettestatus())
                        .as("check indicatieiaatstgezettestatus")
                        .isEqualTo(actual.getIndicatieiaatstgezettestatus())
            )
            .satisfies(e -> assertThat(e.getStatustoelichting()).as("check statustoelichting").isEqualTo(actual.getStatustoelichting()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusUpdatableRelationshipsEquals(Status expected, Status actual) {
        assertThat(expected)
            .as("Verify Status relationships")
            .satisfies(e -> assertThat(e.getIsvanStatustype()).as("check isvanStatustype").isEqualTo(actual.getIsvanStatustype()))
            .satisfies(e -> assertThat(e.getHeeftZaak()).as("check heeftZaak").isEqualTo(actual.getHeeftZaak()));
    }
}
