package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TegenprestatiehoogteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTegenprestatiehoogteAllPropertiesEquals(Tegenprestatiehoogte expected, Tegenprestatiehoogte actual) {
        assertTegenprestatiehoogteAutoGeneratedPropertiesEquals(expected, actual);
        assertTegenprestatiehoogteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTegenprestatiehoogteAllUpdatablePropertiesEquals(Tegenprestatiehoogte expected, Tegenprestatiehoogte actual) {
        assertTegenprestatiehoogteUpdatableFieldsEquals(expected, actual);
        assertTegenprestatiehoogteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTegenprestatiehoogteAutoGeneratedPropertiesEquals(Tegenprestatiehoogte expected, Tegenprestatiehoogte actual) {
        assertThat(expected)
            .as("Verify Tegenprestatiehoogte auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTegenprestatiehoogteUpdatableFieldsEquals(Tegenprestatiehoogte expected, Tegenprestatiehoogte actual) {
        assertThat(expected)
            .as("Verify Tegenprestatiehoogte relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTegenprestatiehoogteUpdatableRelationshipsEquals(Tegenprestatiehoogte expected, Tegenprestatiehoogte actual) {}
}
