package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TelefoononderwerpAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefoononderwerpAllPropertiesEquals(Telefoononderwerp expected, Telefoononderwerp actual) {
        assertTelefoononderwerpAutoGeneratedPropertiesEquals(expected, actual);
        assertTelefoononderwerpAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefoononderwerpAllUpdatablePropertiesEquals(Telefoononderwerp expected, Telefoononderwerp actual) {
        assertTelefoononderwerpUpdatableFieldsEquals(expected, actual);
        assertTelefoononderwerpUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefoononderwerpAutoGeneratedPropertiesEquals(Telefoononderwerp expected, Telefoononderwerp actual) {
        assertThat(expected)
            .as("Verify Telefoononderwerp auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefoononderwerpUpdatableFieldsEquals(Telefoononderwerp expected, Telefoononderwerp actual) {
        assertThat(expected)
            .as("Verify Telefoononderwerp relevant properties")
            .satisfies(e -> assertThat(e.getOnderwerp()).as("check onderwerp").isEqualTo(actual.getOnderwerp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTelefoononderwerpUpdatableRelationshipsEquals(Telefoononderwerp expected, Telefoononderwerp actual) {}
}
