package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ToegangsmiddelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToegangsmiddelAllPropertiesEquals(Toegangsmiddel expected, Toegangsmiddel actual) {
        assertToegangsmiddelAutoGeneratedPropertiesEquals(expected, actual);
        assertToegangsmiddelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToegangsmiddelAllUpdatablePropertiesEquals(Toegangsmiddel expected, Toegangsmiddel actual) {
        assertToegangsmiddelUpdatableFieldsEquals(expected, actual);
        assertToegangsmiddelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToegangsmiddelAutoGeneratedPropertiesEquals(Toegangsmiddel expected, Toegangsmiddel actual) {
        assertThat(expected)
            .as("Verify Toegangsmiddel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToegangsmiddelUpdatableFieldsEquals(Toegangsmiddel expected, Toegangsmiddel actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertToegangsmiddelUpdatableRelationshipsEquals(Toegangsmiddel expected, Toegangsmiddel actual) {}
}
