package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UitstroomredensoortAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUitstroomredensoortAllPropertiesEquals(Uitstroomredensoort expected, Uitstroomredensoort actual) {
        assertUitstroomredensoortAutoGeneratedPropertiesEquals(expected, actual);
        assertUitstroomredensoortAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUitstroomredensoortAllUpdatablePropertiesEquals(Uitstroomredensoort expected, Uitstroomredensoort actual) {
        assertUitstroomredensoortUpdatableFieldsEquals(expected, actual);
        assertUitstroomredensoortUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUitstroomredensoortAutoGeneratedPropertiesEquals(Uitstroomredensoort expected, Uitstroomredensoort actual) {
        assertThat(expected)
            .as("Verify Uitstroomredensoort auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUitstroomredensoortUpdatableFieldsEquals(Uitstroomredensoort expected, Uitstroomredensoort actual) {
        assertThat(expected)
            .as("Verify Uitstroomredensoort relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUitstroomredensoortUpdatableRelationshipsEquals(Uitstroomredensoort expected, Uitstroomredensoort actual) {}
}
