package nl.ritense.demo.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class VastgoedobjectTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static Vastgoedobject getVastgoedobjectSample1() {
        return new Vastgoedobject()
            .id(1L)
            .aantaletages("aantaletages1")
            .aantalparkeerplaatsen("aantalparkeerplaatsen1")
            .aantalrioleringen("aantalrioleringen1")
            .adresaanduiding("adresaanduiding1")
            .afgekochteerfpacht("afgekochteerfpacht1")
            .afgesprokenconditiescore("afgesprokenconditiescore1")
            .asbestrapportageaanwezig("asbestrapportageaanwezig1")
            .bestemmingsplan("bestemmingsplan1")
            .bouwjaar("bouwjaar1")
            .bouwwerk("bouwwerk1")
            .bovenliggendniveau("bovenliggendniveau1")
            .bovenliggendniveaucode("bovenliggendniveaucode1")
            .brutovloeroppervlakte("brutovloeroppervlakte1")
            .co2uitstoot("co2uitstoot1")
            .conditiescore("conditiescore1")
            .deelportefeuille("deelportefeuille1")
            .energielabel("energielabel1")
            .energieverbruik("energieverbruik1")
            .foto("foto1")
            .gearchiveerd("gearchiveerd1")
            .hoofdstuk("hoofdstuk1")
            .identificatie("identificatie1")
            .jaarlaatsterenovatie("jaarlaatsterenovatie1")
            .locatie("locatie1")
            .monument("monument1")
            .naam("naam1")
            .eobjectstatus("eobjectstatus1")
            .eobjectstatuscode("eobjectstatuscode1")
            .eobjecttype("eobjecttype1")
            .eobjecttypecode("eobjecttypecode1")
            .omschrijving("omschrijving1")
            .onderhoudscategorie("onderhoudscategorie1")
            .oppervlaktekantoor("oppervlaktekantoor1")
            .portefeuille("portefeuille1")
            .portefeuillecode("portefeuillecode1")
            .provincie("provincie1")
            .toelichting("toelichting1")
            .verhuurbaarvloeroppervlak("verhuurbaarvloeroppervlak1")
            .verkoopbaarheid("verkoopbaarheid1")
            .wijk("wijk1");
    }

    public static Vastgoedobject getVastgoedobjectSample2() {
        return new Vastgoedobject()
            .id(2L)
            .aantaletages("aantaletages2")
            .aantalparkeerplaatsen("aantalparkeerplaatsen2")
            .aantalrioleringen("aantalrioleringen2")
            .adresaanduiding("adresaanduiding2")
            .afgekochteerfpacht("afgekochteerfpacht2")
            .afgesprokenconditiescore("afgesprokenconditiescore2")
            .asbestrapportageaanwezig("asbestrapportageaanwezig2")
            .bestemmingsplan("bestemmingsplan2")
            .bouwjaar("bouwjaar2")
            .bouwwerk("bouwwerk2")
            .bovenliggendniveau("bovenliggendniveau2")
            .bovenliggendniveaucode("bovenliggendniveaucode2")
            .brutovloeroppervlakte("brutovloeroppervlakte2")
            .co2uitstoot("co2uitstoot2")
            .conditiescore("conditiescore2")
            .deelportefeuille("deelportefeuille2")
            .energielabel("energielabel2")
            .energieverbruik("energieverbruik2")
            .foto("foto2")
            .gearchiveerd("gearchiveerd2")
            .hoofdstuk("hoofdstuk2")
            .identificatie("identificatie2")
            .jaarlaatsterenovatie("jaarlaatsterenovatie2")
            .locatie("locatie2")
            .monument("monument2")
            .naam("naam2")
            .eobjectstatus("eobjectstatus2")
            .eobjectstatuscode("eobjectstatuscode2")
            .eobjecttype("eobjecttype2")
            .eobjecttypecode("eobjecttypecode2")
            .omschrijving("omschrijving2")
            .onderhoudscategorie("onderhoudscategorie2")
            .oppervlaktekantoor("oppervlaktekantoor2")
            .portefeuille("portefeuille2")
            .portefeuillecode("portefeuillecode2")
            .provincie("provincie2")
            .toelichting("toelichting2")
            .verhuurbaarvloeroppervlak("verhuurbaarvloeroppervlak2")
            .verkoopbaarheid("verkoopbaarheid2")
            .wijk("wijk2");
    }

    public static Vastgoedobject getVastgoedobjectRandomSampleGenerator() {
        return new Vastgoedobject()
            .id(longCount.incrementAndGet())
            .aantaletages(UUID.randomUUID().toString())
            .aantalparkeerplaatsen(UUID.randomUUID().toString())
            .aantalrioleringen(UUID.randomUUID().toString())
            .adresaanduiding(UUID.randomUUID().toString())
            .afgekochteerfpacht(UUID.randomUUID().toString())
            .afgesprokenconditiescore(UUID.randomUUID().toString())
            .asbestrapportageaanwezig(UUID.randomUUID().toString())
            .bestemmingsplan(UUID.randomUUID().toString())
            .bouwjaar(UUID.randomUUID().toString())
            .bouwwerk(UUID.randomUUID().toString())
            .bovenliggendniveau(UUID.randomUUID().toString())
            .bovenliggendniveaucode(UUID.randomUUID().toString())
            .brutovloeroppervlakte(UUID.randomUUID().toString())
            .co2uitstoot(UUID.randomUUID().toString())
            .conditiescore(UUID.randomUUID().toString())
            .deelportefeuille(UUID.randomUUID().toString())
            .energielabel(UUID.randomUUID().toString())
            .energieverbruik(UUID.randomUUID().toString())
            .foto(UUID.randomUUID().toString())
            .gearchiveerd(UUID.randomUUID().toString())
            .hoofdstuk(UUID.randomUUID().toString())
            .identificatie(UUID.randomUUID().toString())
            .jaarlaatsterenovatie(UUID.randomUUID().toString())
            .locatie(UUID.randomUUID().toString())
            .monument(UUID.randomUUID().toString())
            .naam(UUID.randomUUID().toString())
            .eobjectstatus(UUID.randomUUID().toString())
            .eobjectstatuscode(UUID.randomUUID().toString())
            .eobjecttype(UUID.randomUUID().toString())
            .eobjecttypecode(UUID.randomUUID().toString())
            .omschrijving(UUID.randomUUID().toString())
            .onderhoudscategorie(UUID.randomUUID().toString())
            .oppervlaktekantoor(UUID.randomUUID().toString())
            .portefeuille(UUID.randomUUID().toString())
            .portefeuillecode(UUID.randomUUID().toString())
            .provincie(UUID.randomUUID().toString())
            .toelichting(UUID.randomUUID().toString())
            .verhuurbaarvloeroppervlak(UUID.randomUUID().toString())
            .verkoopbaarheid(UUID.randomUUID().toString())
            .wijk(UUID.randomUUID().toString());
    }
}
