package nl.ritense.demo.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class VerhardingsobjectTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static Verhardingsobject getVerhardingsobjectSample1() {
        return new Verhardingsobject()
            .id(1L)
            .aanleghoogte("aanleghoogte1")
            .aanofvrijliggend("aanofvrijliggend1")
            .aantaldeklagen("aantaldeklagen1")
            .aantalonderlagen("aantalonderlagen1")
            .aantaltussenlagen("aantaltussenlagen1")
            .afmeting("afmeting1")
            .belasting("belasting1")
            .bergendvermogen("bergendvermogen1")
            .bgtfysiekvoorkomen("bgtfysiekvoorkomen1")
            .breedte("breedte1")
            .dikteconstructie("dikteconstructie1")
            .formaat("formaat1")
            .fysiekvoorkomenimgeo("fysiekvoorkomenimgeo1")
            .jaarconserveren("jaarconserveren1")
            .jaaronderhouduitgevoerd("jaaronderhouduitgevoerd1")
            .jaarpraktischeinde("jaarpraktischeinde1")
            .kleur("kleur1")
            .kwaliteitsniveauactueel("kwaliteitsniveauactueel1")
            .kwaliteitsniveaugewenst("kwaliteitsniveaugewenst1")
            .lengte("lengte1")
            .lengtekunstgras("lengtekunstgras1")
            .lengtevoegen("lengtevoegen1")
            .levensduur("levensduur1")
            .materiaal("materiaal1")
            .maximalevalhoogte("maximalevalhoogte1")
            .omtrek("omtrek1")
            .ondergrondcode("ondergrondcode1")
            .oppervlakte("oppervlakte1")
            .optalud("optalud1")
            .plaatsorientatie("plaatsorientatie1")
            .prijsaanschaf("prijsaanschaf1")
            .rijstrook("rijstrook1")
            .soortvoeg("soortvoeg1")
            .toelichtinggemengdebestrating("toelichtinggemengdebestrating1")
            .type("type1")
            .typeconstructie("typeconstructie1")
            .typefundering("typefundering1")
            .typeplus("typeplus1")
            .typeplus2("typeplus21")
            .typerijstrook("typerijstrook1")
            .typevoeg("typevoeg1")
            .typevoegvulling("typevoegvulling1")
            .vegen("vegen1")
            .verhardingsobjectconstructielaag("verhardingsobjectconstructielaag1")
            .verhardingsobjectmodaliteit("verhardingsobjectmodaliteit1")
            .verhardingsobjectrand("verhardingsobjectrand1")
            .verhardingsobjectwegfunctie("verhardingsobjectwegfunctie1")
            .vulmateriaalkunstgras("vulmateriaalkunstgras1")
            .waterdoorlatendheid("waterdoorlatendheid1")
            .wegas("wegas1")
            .wegcategoriedv("wegcategoriedv1")
            .wegcategoriedvplus("wegcategoriedvplus1")
            .wegnummer("wegnummer1")
            .wegtypebestaand("wegtypebestaand1")
            .wegvak("wegvak1")
            .wegvaknummer("wegvaknummer1");
    }

    public static Verhardingsobject getVerhardingsobjectSample2() {
        return new Verhardingsobject()
            .id(2L)
            .aanleghoogte("aanleghoogte2")
            .aanofvrijliggend("aanofvrijliggend2")
            .aantaldeklagen("aantaldeklagen2")
            .aantalonderlagen("aantalonderlagen2")
            .aantaltussenlagen("aantaltussenlagen2")
            .afmeting("afmeting2")
            .belasting("belasting2")
            .bergendvermogen("bergendvermogen2")
            .bgtfysiekvoorkomen("bgtfysiekvoorkomen2")
            .breedte("breedte2")
            .dikteconstructie("dikteconstructie2")
            .formaat("formaat2")
            .fysiekvoorkomenimgeo("fysiekvoorkomenimgeo2")
            .jaarconserveren("jaarconserveren2")
            .jaaronderhouduitgevoerd("jaaronderhouduitgevoerd2")
            .jaarpraktischeinde("jaarpraktischeinde2")
            .kleur("kleur2")
            .kwaliteitsniveauactueel("kwaliteitsniveauactueel2")
            .kwaliteitsniveaugewenst("kwaliteitsniveaugewenst2")
            .lengte("lengte2")
            .lengtekunstgras("lengtekunstgras2")
            .lengtevoegen("lengtevoegen2")
            .levensduur("levensduur2")
            .materiaal("materiaal2")
            .maximalevalhoogte("maximalevalhoogte2")
            .omtrek("omtrek2")
            .ondergrondcode("ondergrondcode2")
            .oppervlakte("oppervlakte2")
            .optalud("optalud2")
            .plaatsorientatie("plaatsorientatie2")
            .prijsaanschaf("prijsaanschaf2")
            .rijstrook("rijstrook2")
            .soortvoeg("soortvoeg2")
            .toelichtinggemengdebestrating("toelichtinggemengdebestrating2")
            .type("type2")
            .typeconstructie("typeconstructie2")
            .typefundering("typefundering2")
            .typeplus("typeplus2")
            .typeplus2("typeplus22")
            .typerijstrook("typerijstrook2")
            .typevoeg("typevoeg2")
            .typevoegvulling("typevoegvulling2")
            .vegen("vegen2")
            .verhardingsobjectconstructielaag("verhardingsobjectconstructielaag2")
            .verhardingsobjectmodaliteit("verhardingsobjectmodaliteit2")
            .verhardingsobjectrand("verhardingsobjectrand2")
            .verhardingsobjectwegfunctie("verhardingsobjectwegfunctie2")
            .vulmateriaalkunstgras("vulmateriaalkunstgras2")
            .waterdoorlatendheid("waterdoorlatendheid2")
            .wegas("wegas2")
            .wegcategoriedv("wegcategoriedv2")
            .wegcategoriedvplus("wegcategoriedvplus2")
            .wegnummer("wegnummer2")
            .wegtypebestaand("wegtypebestaand2")
            .wegvak("wegvak2")
            .wegvaknummer("wegvaknummer2");
    }

    public static Verhardingsobject getVerhardingsobjectRandomSampleGenerator() {
        return new Verhardingsobject()
            .id(longCount.incrementAndGet())
            .aanleghoogte(UUID.randomUUID().toString())
            .aanofvrijliggend(UUID.randomUUID().toString())
            .aantaldeklagen(UUID.randomUUID().toString())
            .aantalonderlagen(UUID.randomUUID().toString())
            .aantaltussenlagen(UUID.randomUUID().toString())
            .afmeting(UUID.randomUUID().toString())
            .belasting(UUID.randomUUID().toString())
            .bergendvermogen(UUID.randomUUID().toString())
            .bgtfysiekvoorkomen(UUID.randomUUID().toString())
            .breedte(UUID.randomUUID().toString())
            .dikteconstructie(UUID.randomUUID().toString())
            .formaat(UUID.randomUUID().toString())
            .fysiekvoorkomenimgeo(UUID.randomUUID().toString())
            .jaarconserveren(UUID.randomUUID().toString())
            .jaaronderhouduitgevoerd(UUID.randomUUID().toString())
            .jaarpraktischeinde(UUID.randomUUID().toString())
            .kleur(UUID.randomUUID().toString())
            .kwaliteitsniveauactueel(UUID.randomUUID().toString())
            .kwaliteitsniveaugewenst(UUID.randomUUID().toString())
            .lengte(UUID.randomUUID().toString())
            .lengtekunstgras(UUID.randomUUID().toString())
            .lengtevoegen(UUID.randomUUID().toString())
            .levensduur(UUID.randomUUID().toString())
            .materiaal(UUID.randomUUID().toString())
            .maximalevalhoogte(UUID.randomUUID().toString())
            .omtrek(UUID.randomUUID().toString())
            .ondergrondcode(UUID.randomUUID().toString())
            .oppervlakte(UUID.randomUUID().toString())
            .optalud(UUID.randomUUID().toString())
            .plaatsorientatie(UUID.randomUUID().toString())
            .prijsaanschaf(UUID.randomUUID().toString())
            .rijstrook(UUID.randomUUID().toString())
            .soortvoeg(UUID.randomUUID().toString())
            .toelichtinggemengdebestrating(UUID.randomUUID().toString())
            .type(UUID.randomUUID().toString())
            .typeconstructie(UUID.randomUUID().toString())
            .typefundering(UUID.randomUUID().toString())
            .typeplus(UUID.randomUUID().toString())
            .typeplus2(UUID.randomUUID().toString())
            .typerijstrook(UUID.randomUUID().toString())
            .typevoeg(UUID.randomUUID().toString())
            .typevoegvulling(UUID.randomUUID().toString())
            .vegen(UUID.randomUUID().toString())
            .verhardingsobjectconstructielaag(UUID.randomUUID().toString())
            .verhardingsobjectmodaliteit(UUID.randomUUID().toString())
            .verhardingsobjectrand(UUID.randomUUID().toString())
            .verhardingsobjectwegfunctie(UUID.randomUUID().toString())
            .vulmateriaalkunstgras(UUID.randomUUID().toString())
            .waterdoorlatendheid(UUID.randomUUID().toString())
            .wegas(UUID.randomUUID().toString())
            .wegcategoriedv(UUID.randomUUID().toString())
            .wegcategoriedvplus(UUID.randomUUID().toString())
            .wegnummer(UUID.randomUUID().toString())
            .wegtypebestaand(UUID.randomUUID().toString())
            .wegvak(UUID.randomUUID().toString())
            .wegvaknummer(UUID.randomUUID().toString());
    }
}
