package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VerlofsoortAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerlofsoortAllPropertiesEquals(Verlofsoort expected, Verlofsoort actual) {
        assertVerlofsoortAutoGeneratedPropertiesEquals(expected, actual);
        assertVerlofsoortAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerlofsoortAllUpdatablePropertiesEquals(Verlofsoort expected, Verlofsoort actual) {
        assertVerlofsoortUpdatableFieldsEquals(expected, actual);
        assertVerlofsoortUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerlofsoortAutoGeneratedPropertiesEquals(Verlofsoort expected, Verlofsoort actual) {
        assertThat(expected)
            .as("Verify Verlofsoort auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerlofsoortUpdatableFieldsEquals(Verlofsoort expected, Verlofsoort actual) {
        assertThat(expected)
            .as("Verify Verlofsoort relevant properties")
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerlofsoortUpdatableRelationshipsEquals(Verlofsoort expected, Verlofsoort actual) {}
}
