package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VthmeldingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVthmeldingAllPropertiesEquals(Vthmelding expected, Vthmelding actual) {
        assertVthmeldingAutoGeneratedPropertiesEquals(expected, actual);
        assertVthmeldingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVthmeldingAllUpdatablePropertiesEquals(Vthmelding expected, Vthmelding actual) {
        assertVthmeldingUpdatableFieldsEquals(expected, actual);
        assertVthmeldingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVthmeldingAutoGeneratedPropertiesEquals(Vthmelding expected, Vthmelding actual) {
        assertThat(expected)
            .as("Verify Vthmelding auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVthmeldingUpdatableFieldsEquals(Vthmelding expected, Vthmelding actual) {
        assertThat(expected)
            .as("Verify Vthmelding relevant properties")
            .satisfies(e -> assertThat(e.getActiviteit()).as("check activiteit").isEqualTo(actual.getActiviteit()))
            .satisfies(e -> assertThat(e.getBeoordeling()).as("check beoordeling").isEqualTo(actual.getBeoordeling()))
            .satisfies(e -> assertThat(e.getDatumseponering()).as("check datumseponering").isEqualTo(actual.getDatumseponering()))
            .satisfies(e -> assertThat(e.getDatumtijdtot()).as("check datumtijdtot").isEqualTo(actual.getDatumtijdtot()))
            .satisfies(e -> assertThat(e.getGeseponeerd()).as("check geseponeerd").isEqualTo(actual.getGeseponeerd()))
            .satisfies(e -> assertThat(e.getLocatie()).as("check locatie").isEqualTo(actual.getLocatie()))
            .satisfies(
                e -> assertThat(e.getOrganisatieonderdeel()).as("check organisatieonderdeel").isEqualTo(actual.getOrganisatieonderdeel())
            )
            .satisfies(e -> assertThat(e.getOvertredingscode()).as("check overtredingscode").isEqualTo(actual.getOvertredingscode()))
            .satisfies(e -> assertThat(e.getOvertredingsgroep()).as("check overtredingsgroep").isEqualTo(actual.getOvertredingsgroep()))
            .satisfies(e -> assertThat(e.getReferentienummer()).as("check referentienummer").isEqualTo(actual.getReferentienummer()))
            .satisfies(e -> assertThat(e.getResultaat()).as("check resultaat").isEqualTo(actual.getResultaat()))
            .satisfies(e -> assertThat(e.getSoortvthmelding()).as("check soortvthmelding").isEqualTo(actual.getSoortvthmelding()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getStraatnaam()).as("check straatnaam").isEqualTo(actual.getStraatnaam()))
            .satisfies(e -> assertThat(e.getTaaktype()).as("check taaktype").isEqualTo(actual.getTaaktype()))
            .satisfies(e -> assertThat(e.getZaaknummer()).as("check zaaknummer").isEqualTo(actual.getZaaknummer()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVthmeldingUpdatableRelationshipsEquals(Vthmelding expected, Vthmelding actual) {}
}
