package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WeginrichtingsobjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeginrichtingsobjectAllPropertiesEquals(Weginrichtingsobject expected, Weginrichtingsobject actual) {
        assertWeginrichtingsobjectAutoGeneratedPropertiesEquals(expected, actual);
        assertWeginrichtingsobjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeginrichtingsobjectAllUpdatablePropertiesEquals(Weginrichtingsobject expected, Weginrichtingsobject actual) {
        assertWeginrichtingsobjectUpdatableFieldsEquals(expected, actual);
        assertWeginrichtingsobjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeginrichtingsobjectAutoGeneratedPropertiesEquals(Weginrichtingsobject expected, Weginrichtingsobject actual) {
        assertThat(expected)
            .as("Verify Weginrichtingsobject auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeginrichtingsobjectUpdatableFieldsEquals(Weginrichtingsobject expected, Weginrichtingsobject actual) {
        assertThat(expected)
            .as("Verify Weginrichtingsobject relevant properties")
            .satisfies(e -> assertThat(e.getAanleghoogte()).as("check aanleghoogte").isEqualTo(actual.getAanleghoogte()))
            .satisfies(e -> assertThat(e.getBreedte()).as("check breedte").isEqualTo(actual.getBreedte()))
            .satisfies(e -> assertThat(e.getHoogte()).as("check hoogte").isEqualTo(actual.getHoogte()))
            .satisfies(e -> assertThat(e.getJaarconserveren()).as("check jaarconserveren").isEqualTo(actual.getJaarconserveren()))
            .satisfies(
                e ->
                    assertThat(e.getJaaronderhouduitgevoerd())
                        .as("check jaaronderhouduitgevoerd")
                        .isEqualTo(actual.getJaaronderhouduitgevoerd())
            )
            .satisfies(
                e ->
                    assertThat(e.getKwaliteitsniveauactueel())
                        .as("check kwaliteitsniveauactueel")
                        .isEqualTo(actual.getKwaliteitsniveauactueel())
            )
            .satisfies(
                e ->
                    assertThat(e.getKwaliteitsniveaugewenst())
                        .as("check kwaliteitsniveaugewenst")
                        .isEqualTo(actual.getKwaliteitsniveaugewenst())
            )
            .satisfies(e -> assertThat(e.getLengte()).as("check lengte").isEqualTo(actual.getLengte()))
            .satisfies(e -> assertThat(e.getLeverancier()).as("check leverancier").isEqualTo(actual.getLeverancier()))
            .satisfies(e -> assertThat(e.getMateriaal()).as("check materiaal").isEqualTo(actual.getMateriaal()))
            .satisfies(e -> assertThat(e.getOppervlakte()).as("check oppervlakte").isEqualTo(actual.getOppervlakte()))
            .satisfies(
                e ->
                    assertThat(e.getWeginrichtingsobjectwegfunctie())
                        .as("check weginrichtingsobjectwegfunctie")
                        .isEqualTo(actual.getWeginrichtingsobjectwegfunctie())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeginrichtingsobjectUpdatableRelationshipsEquals(Weginrichtingsobject expected, Weginrichtingsobject actual) {}
}
