package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ZelfredzaamheidmatrixAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZelfredzaamheidmatrixAllPropertiesEquals(Zelfredzaamheidmatrix expected, Zelfredzaamheidmatrix actual) {
        assertZelfredzaamheidmatrixAutoGeneratedPropertiesEquals(expected, actual);
        assertZelfredzaamheidmatrixAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZelfredzaamheidmatrixAllUpdatablePropertiesEquals(
        Zelfredzaamheidmatrix expected,
        Zelfredzaamheidmatrix actual
    ) {
        assertZelfredzaamheidmatrixUpdatableFieldsEquals(expected, actual);
        assertZelfredzaamheidmatrixUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZelfredzaamheidmatrixAutoGeneratedPropertiesEquals(
        Zelfredzaamheidmatrix expected,
        Zelfredzaamheidmatrix actual
    ) {
        assertThat(expected)
            .as("Verify Zelfredzaamheidmatrix auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZelfredzaamheidmatrixUpdatableFieldsEquals(Zelfredzaamheidmatrix expected, Zelfredzaamheidmatrix actual) {
        assertThat(expected)
            .as("Verify Zelfredzaamheidmatrix relevant properties")
            .satisfies(
                e -> assertThat(e.getDatumeindegeldigheid()).as("check datumeindegeldigheid").isEqualTo(actual.getDatumeindegeldigheid())
            )
            .satisfies(
                e -> assertThat(e.getDatumstartgeldigheid()).as("check datumstartgeldigheid").isEqualTo(actual.getDatumstartgeldigheid())
            )
            .satisfies(e -> assertThat(e.getNaam()).as("check naam").isEqualTo(actual.getNaam()))
            .satisfies(e -> assertThat(e.getOmschrijving()).as("check omschrijving").isEqualTo(actual.getOmschrijving()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZelfredzaamheidmatrixUpdatableRelationshipsEquals(
        Zelfredzaamheidmatrix expected,
        Zelfredzaamheidmatrix actual
    ) {}
}
