package nl.ritense.demo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ZiekmeldingleerlingenvervoerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZiekmeldingleerlingenvervoerAllPropertiesEquals(
        Ziekmeldingleerlingenvervoer expected,
        Ziekmeldingleerlingenvervoer actual
    ) {
        assertZiekmeldingleerlingenvervoerAutoGeneratedPropertiesEquals(expected, actual);
        assertZiekmeldingleerlingenvervoerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZiekmeldingleerlingenvervoerAllUpdatablePropertiesEquals(
        Ziekmeldingleerlingenvervoer expected,
        Ziekmeldingleerlingenvervoer actual
    ) {
        assertZiekmeldingleerlingenvervoerUpdatableFieldsEquals(expected, actual);
        assertZiekmeldingleerlingenvervoerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZiekmeldingleerlingenvervoerAutoGeneratedPropertiesEquals(
        Ziekmeldingleerlingenvervoer expected,
        Ziekmeldingleerlingenvervoer actual
    ) {
        assertThat(expected)
            .as("Verify Ziekmeldingleerlingenvervoer auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZiekmeldingleerlingenvervoerUpdatableFieldsEquals(
        Ziekmeldingleerlingenvervoer expected,
        Ziekmeldingleerlingenvervoer actual
    ) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZiekmeldingleerlingenvervoerUpdatableRelationshipsEquals(
        Ziekmeldingleerlingenvervoer expected,
        Ziekmeldingleerlingenvervoer actual
    ) {}
}
