import dayjs from 'dayjs';
import { IPand } from 'app/shared/model/pand.model';
import { IKostenplaats } from 'app/shared/model/kostenplaats.model';

export interface IVastgoedobject {
  id?: number;
  aantaletages?: string | null;
  aantalparkeerplaatsen?: string | null;
  aantalrioleringen?: string | null;
  adresaanduiding?: string | null;
  afgekochteerfpacht?: string | null;
  afgesprokenconditiescore?: string | null;
  afkoopwaarde?: number | null;
  asbestrapportageaanwezig?: string | null;
  bedragaankoop?: number | null;
  bestemmingsplan?: string | null;
  boekwaarde?: number | null;
  bouwjaar?: string | null;
  bouwwerk?: string | null;
  bovenliggendniveau?: string | null;
  bovenliggendniveaucode?: string | null;
  brutovloeroppervlakte?: string | null;
  co2uitstoot?: string | null;
  conditiescore?: string | null;
  datumafstoten?: dayjs.Dayjs | null;
  datumberekeningoppervlak?: dayjs.Dayjs | null;
  datumeigendom?: dayjs.Dayjs | null;
  datumverkoop?: dayjs.Dayjs | null;
  deelportefeuille?: string | null;
  energiekosten?: number | null;
  energielabel?: string | null;
  energieverbruik?: string | null;
  fiscalewaarde?: number | null;
  foto?: string | null;
  gearchiveerd?: string | null;
  herbouwwaarde?: number | null;
  hoofdstuk?: string | null;
  identificatie?: string | null;
  jaarlaatsterenovatie?: string | null;
  locatie?: string | null;
  marktwaarde?: number | null;
  monument?: string | null;
  naam?: string | null;
  eobjectstatus?: string | null;
  eobjectstatuscode?: string | null;
  eobjecttype?: string | null;
  eobjecttypecode?: string | null;
  omschrijving?: string | null;
  onderhoudscategorie?: string | null;
  oppervlaktekantoor?: string | null;
  portefeuille?: string | null;
  portefeuillecode?: string | null;
  provincie?: string | null;
  toelichting?: string | null;
  verhuurbaarvloeroppervlak?: string | null;
  verkoopbaarheid?: string | null;
  verkoopbedrag?: number | null;
  verzekerdewaarde?: number | null;
  waardegrond?: number | null;
  waardeopstal?: number | null;
  wijk?: string | null;
  wozwaarde?: number | null;
  betreftPand?: IPand | null;
  heeftKostenplaats?: IKostenplaats | null;
}

export const defaultValue: Readonly<IVastgoedobject> = {};
